# Generated by Django 5.0.3 on 2024-05-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='current_distance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='target_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
