# Generated by Django 5.0.3 on 2024-05-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_request_current_distance_request_target_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Motorcycle', 'Motorcycle'), ('Bajaj', 'Bajaj'), ('Automatic Car', 'Automatic Car'), ('Manual Car', 'Manual Car')], max_length=50),
        ),
    ]
