# Generated by Django 5.0.3 on 2024-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_alter_request_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='phone_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='problem_description',
            field=models.TextField(null=True),
        ),
    ]
