# Generated by Django 5.0.3 on 2024-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_request_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
